name: Frontend CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies

        run: cd frontend && pnpm install

      - name: Run linter
        run: cd frontend && pnpm lint || true


      - name: Build frontend
        run: cd frontend && npm run build

      # Optional: Deploy to Vercel (automatic if Vercel GitHub integration is enabled)
